#!/usr/bin/env bash

set -euo pipefail

prefix=$1

for compiler in lualatex xelatex; do
  mkdir -p out/${compiler}
  ${compiler} --halt-on-error --output-directory=out/${compiler} "${prefix}.tex"
done
