#!/usr/bin/env bash

set -euo pipefail

if [[ ${1:-} == '--copy' ]]; then
  copy=1; shift
fi

prefix=${1%.tex}

copy_host=nice.local

compilers=(
  lualatex
  pdflatex
  xelatex
)

for compiler in "${compilers[@]}"; do
  copy() {
    if [[ $copy -eq 1 ]]; then
      scp "out/${compiler}/${prefix}.pdf" "${copy_host}:${prefix}.${compiler}.pdf"
    fi
  }

  failed() {
    bat "${out_dir}/stdout.log"
  }

  out_dir="out/${compiler}"
  mkdir -p "${out_dir}"

  echo "-----------------------"
  echo "----- ${compiler} -----"
  ${compiler} \
    --halt-on-error \
    --output-directory="${out_dir}" \
    "${prefix}.tex" \
    >"${out_dir}/stdout.log" \
    && copy \
    || failed
  echo "-----------------------"
done
